Acceptance tests
rakastettu13/qna pull request #3
Opened 2021-08-03 14:00 UTC by rakastettu13

2021-08-04 09:11 UTC, VidgarVii commented on spec/controllers/answers_controller_spec.rb
> +        expect { deletion_request }.to change(Answer, :count).by(-1)
можно сразу проверять что ответ удаляется текущего юзера

2021-08-04 09:11 UTC, VidgarVii commented on spec/controllers/questions_controller_spec.rb
> +        expect { deletion_request }.to change(Question, :count).by(-1)
тоже самое. лучше добавить проверку что удаляется вопрос текущего юзера, а не любой

2021-08-04 09:11 UTC, VidgarVii commented on spec/features/answers/create_spec.rb
> +      expect(page).to have_content 'Your answer has been sent successfully.'
тут мы проверили только флэш сообщение. Лучше поискать на странице текст ответа и написать проверку для него

2021-08-04 09:11 UTC, VidgarVii commented on spec/features/question/create_spec.rb
> +      expect(page).to have_content 'Your question successfully created.'
тоже самое проверяй на странице текст вопроса. И лучше искать конкретно в заданной области странице (там где должен появиться текст), а не по всей странице page

2021-08-04 10:20 UTC, VidgarVii requested changes

2021-08-04 10:20 UTC, VidgarVii commented on spec/features/answers/destroy_spec.rb
> +  end
не хватает сценарий дла неаутентифицированного юзера

2021-08-04 10:20 UTC, VidgarVii commented on spec/features/question/destroy_spec.rb
> +  end
не хватает сценарий дла неаутентифицированного юзера

2021-08-04 10:21 UTC, VidgarVii requested changes

2021-08-04 10:21 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    if answer.author == current_user
1 Вот такие проверки лучше делать по user_id, чтобы избежать n+1 запроса (особенно в видах)

2 т.к. такие проверки будут нужны много где, лучше их вынести в метод User#author_of? и не забыть протестировать

2021-08-05 13:10 UTC, VidgarVii commented on app/models/user.rb
> +  end
мб лучше resource или object вместо something?

2021-08-05 13:10 UTC, VidgarVii commented on spec/models/user_spec.rb
> +  end
можно так. по моему выглядет лучше
```
describe '#author_of?' do
    subject { user.author_of?(resource) }

    let(:user) { create(:user) }

    context 'when user is the author' do
      let(:resource) { create(:question, author: user) }

      it { is_expected.to be_truthy }
    end

    context 'when user is not the author' do
      let(:resource) { create(:question) }

      it { is_expected.to be_falsey }
    end
  end
```
субъект это то что тестируем
контекст это то что меняется в тестах (параметры метода или запроса например)

2021-08-05 13:14 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    return unless elem.valid? && elem.author == current_user
здесь проверку на автора надо заменить на вызов метода author_of

2021-08-05 13:17 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      flash[:alert] = "Title/Body can't be blank"
вот так не стоит делать вывод ошибок валидации. надо сделать его через рендер паршала для ошибок, потому что валидации могут измениться и придется контроллер переписывать, а это по идее, не его ответсвенность (то же самое для контроллера ответов)

2021-08-05 13:17 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +            send("#{elem_class}_path".to_sym, id: elem),
вместо send лучше использовать polymorphic_path 
https://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html

2021-08-07 10:38 UTC, VidgarVii commented on spec/controllers/answers_controller_spec.rb
> +                                author_id: user.id,
1 в контроллере мы ни как не обрабатываем параметр author_id
2 автором ответа/вопроса является текущий аутентифицированный пользователь. Его мы получаем через devise . Мы не передаём больше ни каких параметров author_id при создании ресурсов.
получается смело можно убрать этот параметр запроса author_id: user.id, и тесты останутся зелеными

2021-08-07 10:50 UTC, VidgarVii commented on spec/features/answers/destroy_spec.rb
> +    expect(page).to have_content 'Your answer successfully deleted.'
фича-тестах на удаление вопроса /ответа перед удалением хорошо бы добавить проверку, что удаляемый текст есть на странице, чтобы избежать ложно-положительного теста.

2021-08-07 11:01 UTC, VidgarVii commented on spec/features/answers/destroy_spec.rb
> +    expect(page).to have_content 'Your answer successfully deleted.'
сейчас ты проверяешь влэш сообщение

2021-08-07 11:31 UTC, rakastettu13 commented on spec/features/question/index_spec.rb
> +      [question1, question2].each do |question|
почему-то не ругался

2021-08-09 05:52 UTC, VidgarVii commented on spec/features/question/index_spec.rb
> +      [question1, question2].each do |question|
для rspec настраивать надо

2021-08-11 12:36 UTC, merged